$:
  vscode:
    - docker:
        build: 
          dockerfile: .ide/Dockerfile
          by:
            - .ide/extensions.json
            - .ide/languagepacks.json
            - .ide/user.argv.json
      services:
        - vscode
      stages:
        - name: ready
          type: vscode:go