$:
  api_trigger_vscode:
    clouddev:
      docker:
        build: 
          dockerfile: .ide/Dockerfile
          by:
            - .ide/extensions.json
            - .ide/languagepacks.json
            - .ide/user.argv.json

      services:
        - vscode
      stages:
        - name: ready
          type: vscode:go
    
.release-binary: &release-binary
  docker:
    image: golang:alpine
    volumes:
      - main:/root/.cache/go-build:copy-on-write
  stages:
    - name: build-binaries
      ifModify: 
        - "**/*.go"
        - "go.mod"
        - ".build/*-binaries.sh"
      script: sh .build/build-binaries.sh
    - name: push-binaries
      ifModify:
        - "**/*.go"
        - "go.mod"
        - ".build/*-binaries.sh"
      script: sh .build/push-binaries.sh

.mirror-to-github: &mirror-to-github
  docker:
    image: alpine/git:latest
  imports: https://e.coding.net/visoft/imetnide/keys/blob/master/ci-keys
  stages:
    - name: mirror-to-github
      script: /bin/sh .build/mirror-to-github.sh
    - name: mirror-to-gitcode
      script: /bin/sh .build/mirror-to-gitcode.sh

'rel-*':
  tag_push:
    - *release-binary
'main':
  push:
    - *release-binary