$:
  api_trigger_vscode:
    clouddev:
      docker:
        build: .ide/Dockerfile
      services:
        - vscode
      stages:
        - name: ready
          type: vscode:go
    
.release-binary: &release-binary
  docker:
    image: golang:alpine
    volumes:
      - main:/root/.cache/go-build:copy-on-write
  stages:
    - name: build-binaries
      ifModify: 
        - "**/*.go"
        - "go.mod"
      script: sh .build/build-binaries.sh
    - name: push-binaries
      ifModify:
        - "**/*.go"
        - "go.mod"
      script: sh .build/push-binaries.sh

'rel-*':
  tag_push:
    - *release-binary
'main':
  push:
    - *release-binary