$:
  api_trigger_vscode:
    clouddev:
      docker:
        build: .ide/Dockerfile
      services:
        - vscode
      stages:
        - name: ready
          type: vscode:go

.building-binary: &building-binary
    - name: build-binaries
      image: golang:alpine
      script: .build/build-binaries.sh

.release-binary: &release-binary
    - *building-binary
    - name: push-binaries
      script: .build/push-binaries.sh

'rel-*':
  tag_push:
    - stages:
      - *release-binary
'main':
  push:
    - stages:
      - *release-binary